### ISSUE TITLE
Errors while Building kGuard using gcc-4.6.3

### ISSUE THREAD

**Issue by 1Husin-Alhaj** [pmoust/kguard#1]
After many arduous attempts to build **kguard**, all attempts over 100 hours failed ... and almost decided to surrender.
I changed the operating system to an old system so I can use an old version of gcc compiler. 
I installed all that is required with a very careful consideration of the version required.
I installed the following:

- Ubuntu 32bit with gcc 4.6.3 ( and g++ 4.6.3 too)
- gcc-plugin-dev 4.6
- and all the packages that have mentioned in **README** file attached with kguard project. 

When I tried to build the tool, I got a lot of errors ... Over a week I was trying to solve this problem, but to no avail.
 
first of all, I thought that the problem in the g++ version, therefore I upgraded it to g++-6. WHY?
I used NetBeans to write my code (in c language). Netbeans gives an error when I included both files **("basic-block.h" and "rtl.h")**. I really do not know why!. To solve this problem, I add (-std=c11 flag)... Netbeans did not thrown any error for files ("basic-block.h" and "rtl.h") but another error is ocurred:
**cc1: error: unrecognized command line option ‘-std=c11’**
 
I really confused about this. The authors of kguard said kguard must be build with **gcc-4.{5, 6, 7}** only. 
Another errors I have got:

- **unknown type name** .... for a variables which defined inside a plugin's header files!!!!!!!!!
- fatal error: coretypes.h: No such file or directory compilation terminated. Also for gimple.h  rtl.h ....etc  **is not a file or directory** !!!! I set the path to plugin/include very carefully.

 **I pasted a few of errors below:**

 ```
......
/usr/lib/gcc/i686-linux-gnu/4.6/plugin/include/hard-reg-set.h: In function ‘hard_reg_set_iter_set’:
/usr/lib/gcc/i686-linux-gnu/4.6/plugin/include/hard-reg-set.h:545:28: **error**: **‘FIRST_PSEUDO_REGISTER’ undeclared (first use in this function)**
/usr/lib/gcc/i686-linux-gnu/4.6/plugin/include/hard-reg-set.h:545:28: note: each undeclared identifier is reported only once for each function it appears in
/usr/lib/gcc/i686-linux-gnu/4.6/plugin/include/hard-reg-set.h: At top level:
/usr/lib/gcc/i686-linux-gnu/4.6/plugin/include/hard-reg-set.h:583:24: error: ‘FIRST_PSEUDO_REGISTER’ undeclared here (not in a function)
/usr/lib/gcc/i686-linux-gnu/4.6/plugin/include/hard-reg-set.h:644:40: **error: ‘N_REG_CLASSES’ undeclared here (not in a function)**
 
/usr/lib/gcc/i686-linux-gnu/4.6/plugin/include/function.h:223:3: **error: unknown type name ‘CUMULATIVE_ARGS’**
/usr/lib/gcc/i686-linux-gnu/4.6/plugin/include/function.h:705:32: error: unknown type name ‘CUMULATIVE_ARGS’
/usr/lib/gcc/i686-linux-gnu/4.6/plugin/include/function.h:707:38: error: unknown type name ‘CUMULATIVE_ARGS’

and a lot . . .
```
I edit kguard so that kguard.c is just a file the include kguard.h and hase the plugin_init fuction (only) and compiled it ...

![image](https://user-images.githubusercontent.com/17450624/68610694-97371e00-04cd-11ea-8f1e-4e65c837449f.png)

I used the same makefile provided by Kguard. 

I realized that the error comes from the basic-block.h file. I commented it, i.s. removed it) and the .so is produced.
![image](https://user-images.githubusercontent.com/17450624/68610534-3d365880-04cd-11ea-8ed0-ef486f8d0e83.png)

by the way, this is not a solution.
Any help will be very appreciated :)

**Comment by 1Husin-Alhaj** [comment]
I parsed the code line by line and checked the content of header files in plugin/include directory, I found that:
**Unable to resolve identifier to** both (**SELECT_CC_MODE** and **STACK_POINTER_REGNUM**). Meaning that, the gcc version and plugin-dev version that requested to build kguard don't have these two elements. ( based on GNU Compiler Collection (GCC) Internals v4.8, in page 166/722 ... 
"
**VIRTUAL_STACK_DYNAMIC_REGNUM** This points to the location of dynamically allocated memory on the stack immediately after the stack pointer has been adjusted by the amount of memory desired. **This virtual register is replaced by** the sum of the register given by **STACK_POINTER_REGNUM** and the value STACK_DYNAMIC_OFFSET.
"
So, in the README file, the authors wrote:
"
	[*] Dependencies:

		[-] GCC v4.5, v4.6, or v4.7 (versions >=4.8 are not supported).
"
I have used gcc v4.6 with gcc-plugin-dev v4.6.

and... in the header file ... function.h ... it includes the file hard-reg-set.h which is the responsible for this error 
![image](https://user-images.githubusercontent.com/17450624/68657445-fc7c2500-0548-11ea-9942-3e70a6c0d920.png)

**Comment by pmoust** [comment]
I am afraid that I am currently too busy to have a look at this @1Husin-Alhaj - will try to check back in December.

That said, last I checked w/ gcc 4.5, you _should_ be able to compile kguard w/ `make clean all`

**Comment by 1Husin-Alhaj** [comment]
Thank you Mr. Pmoust

**Comment by pmoust** [comment]
@1Husin-Alhaj I got a chance this weekend to go over this, this is how you can trivially get a successful build w/ gcc 4.6.3;

```sh
# Get a clean dev environment and enter it
vagrant init ubuntu/precise64
vagrant up
vagrant ssh
# Install dependencies in the environment
sudo apt-get install gcc git linux-headers-$(uname -r) libbsd-dev libconfig-dev gcc-4.6-plugin-dev
# checkout the repo
git clone https://github.com/pmoust/kguard.git
# build kguard.so
cd kguard && make all
```

The above should get you going.

```sh
vagrant@vagrant-ubuntu-precise-64:~/kguard$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --disable-werror --with-arch-32=i686 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)
```

```sh
vagrant@vagrant-ubuntu-precise-64:~/kguard$ date; file kguard.so
Sat Nov 16 12:44:46 UTC 2019
kguard.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=0x9551947a4cd1af1bd6c4a81895b57d2adc1b2969, not stripped
```

**Comment by pmoust** [comment]
Haven't received any other feedback, so I am closing this as fixed. Re-open if you feel otherwise.
